"""CLI commands for domain management.

Commands:
  datameshy domain onboard  — provision a new domain into the mesh (platform-team command)
  datameshy domain init     — scaffold a new isolated domain repo (domain-team command)
  datameshy domain upgrade  — upgrade an existing domain repo to a new platform version
  datameshy domain list     — list all onboarded domains
  datameshy domain status   — show domain details and product count
"""

from __future__ import annotations

import importlib.resources
import re
import shutil
from pathlib import Path
from typing import Annotated, Optional

import typer
from jinja2 import BaseLoader, Environment
from rich.console import Console
from rich.table import Table

app = typer.Typer(help="Manage mesh domains (onboard, list, status).")
console = Console()

_DOMAIN_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9\-]{0,30}[a-zA-Z0-9]$|^[a-zA-Z0-9]$")
_DOMAINS_TABLE = "mesh-domains"
_PRODUCTS_TABLE = "mesh-products"


def _validate_domain_name(name: str) -> str:
    """Validate domain name: alphanumeric + hyphens, max 32 chars."""
    if len(name) > 32:
        raise typer.BadParameter(f"Domain name must be ≤ 32 characters (got {len(name)}).")
    if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$", name):
        raise typer.BadParameter(
            "Domain name must contain only alphanumeric characters and hyphens, "
            "and must start/end with an alphanumeric character."
        )
    return name


def _get_session_from_ctx(ctx: typer.Context):
    """Retrieve or create a boto3 session from the Typer context."""
    from datameshy.lib.aws_client import get_session

    obj = ctx.ensure_object(dict)
    profile = obj.get("profile")
    region = obj.get("region", "us-east-1")
    return get_session(profile=profile, region=region)


@app.command("onboard")
def domain_onboard(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", help="Domain name (alphanumeric + hyphens, max 32 chars).")],
    account_id: Annotated[str, typer.Option("--account-id", help="AWS account ID for the domain.")],
    owner: Annotated[str, typer.Option("--owner", help="Domain owner email address.")],
    event_bus_arn: Annotated[
        Optional[str],
        typer.Option("--event-bus-arn", help="Central EventBridge event bus ARN.", envvar="MESH_EVENT_BUS_ARN"),
    ] = None,
    dry_run: Annotated[bool, typer.Option("--dry-run", help="Run plan only; do not apply.")] = False,
) -> None:
    """Onboard a new domain into the data mesh.

    This command will:

    \b
    1. Validate domain name and inputs
    2. Scaffold a Terraform environment directory at infra/environments/domain-{name}/
    3. Run terraform plan and show a summary
    4. Prompt for confirmation before applying
    5. Emit a DomainOnboarded event to the central event bus

    Example:

    \b
      datameshy domain onboard \\
        --name sales \\
        --account-id 123456789012 \\
        --owner sales-team@company.com
    """
    # 1. Validate inputs
    _validate_domain_name(name)
    if not re.match(r"^\d{12}$", account_id):
        raise typer.BadParameter(f"account-id must be a 12-digit AWS account ID (got: {account_id}).")
    if "@" not in owner:
        raise typer.BadParameter(f"owner must be a valid email address (got: {owner}).")

    console.print(f"[bold]Onboarding domain:[/bold] [cyan]{name}[/cyan]")
    console.print(f"  Account ID : {account_id}")
    console.print(f"  Owner      : {owner}")

    # 2. Scaffold Terraform environment directory
    env_dir = Path.cwd() / "infra" / "environments" / f"domain-{name}"
    env_dir.mkdir(parents=True, exist_ok=True)

    # Populate terraform.tfvars
    tfvars_content = (
        f'domain      = "{name}"\n'
        f'account_id  = "{account_id}"\n'
        f'owner       = "{owner}"\n'
    )
    tfvars_path = env_dir / "terraform.tfvars"
    tfvars_path.write_text(tfvars_content, encoding="utf-8")

    # Create a minimal main.tf if it doesn't exist
    main_tf = env_dir / "main.tf"
    if not main_tf.exists():
        main_tf.write_text(
            '# Auto-generated by datameshy domain onboard\n'
            '# Customize this file with your domain-specific Terraform configuration.\n\n'
            'module "domain" {\n'
            '  source     = "../../modules/domain-account"\n'
            f'  domain     = "{name}"\n'
            f'  account_id = "{account_id}"\n'
            f'  owner      = "{owner}"\n'
            '}\n',
            encoding="utf-8",
        )

    console.print(f"\n[dim]Terraform environment scaffolded at:[/dim] {env_dir}")

    if dry_run:
        console.print("\n[yellow]--dry-run mode: skipping terraform plan/apply and event emission.[/yellow]")
        console.print(f"\n[green]Domain '{name}' scaffolded.[/green] Review {env_dir} before applying.")
        return

    # 3. Run terraform plan
    from datameshy.lib.terraform_runner import TerraformError, plan

    try:
        console.print("\n[bold]Running terraform plan...[/bold]")
        plan_output = plan(str(env_dir), var_overrides={"domain": name, "account_id": account_id, "owner": owner})
        console.print("[dim]Plan output (credential lines redacted):[/dim]")
        # Show first 40 lines of plan output
        lines = plan_output.splitlines()
        for line in lines[:40]:
            console.print(f"  {line}")
        if len(lines) > 40:
            console.print(f"  [dim]... ({len(lines) - 40} more lines)[/dim]")
    except FileNotFoundError:
        console.print(
            f"[yellow]terraform not found or env directory missing — skipping plan.[/yellow]\n"
            f"[dim]Run `terraform plan` manually in {env_dir}[/dim]"
        )
        plan_output = ""
    except TerraformError as exc:
        console.print(f"[red]terraform plan failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    # 4. Confirm before apply
    if plan_output:
        confirmed = typer.confirm(
            "\nReview the plan above. Apply now?",
            default=False,
        )
        if not confirmed:
            console.print("[yellow]Apply cancelled. Terraform environment is scaffolded and ready.[/yellow]")
            console.print(f"Run manually: cd {env_dir} && terraform apply")
            return

        from datameshy.lib.terraform_runner import apply

        try:
            console.print("\n[bold]Applying...[/bold]")
            apply(str(env_dir), var_overrides={"domain": name, "account_id": account_id, "owner": owner}, auto_approve=True)
            console.print("[green]terraform apply succeeded.[/green]")
        except TerraformError as exc:
            console.print(f"[red]terraform apply failed:[/red] {exc}")
            raise typer.Exit(code=1) from exc

    # 5. Emit DomainOnboarded event
    if event_bus_arn:
        try:
            session = _get_session_from_ctx(ctx)
            from datameshy.lib.aws_client import put_mesh_event

            event_id = put_mesh_event(
                session=session,
                event_bus_arn=event_bus_arn,
                event_type="DomainOnboarded",
                payload={"domain": name, "account_id": account_id, "owner": owner},
            )
            console.print(f"[green]DomainOnboarded event emitted.[/green] event_id={event_id}")
        except Exception as exc:
            console.print(f"[yellow]Warning: could not emit DomainOnboarded event:[/yellow] {exc}")

    # 6. Success summary
    console.print(
        f"\n[bold green]Domain '{name}' onboarded successfully.[/bold green]\n"
        "\nNext steps:\n"
        f"  1. Customize pipeline logic in [cyan]{env_dir}[/cyan]\n"
        "  2. Create your first data product: [cyan]datameshy product create --spec product.yaml[/cyan]\n"
        "  3. List all domains: [cyan]datameshy domain list[/cyan]"
    )


@app.command("init")
def domain_init(
    name: Annotated[str, typer.Option("--name", help="Domain name (alphanumeric + hyphens, max 32 chars).")],
    account_id: Annotated[str, typer.Option("--account-id", help="12-digit AWS account ID for the domain.")],
    owner: Annotated[str, typer.Option("--owner", help="Domain owner email address.")],
    platform_version: Annotated[str, typer.Option("--platform-version", help="Platform version to pin.")] = "1.0.0",
    output_dir: Annotated[Optional[Path], typer.Option("--output-dir", help="Directory to scaffold repo into.")] = None,
) -> None:
    """Scaffold a new isolated domain repo for a domain team.

    This command renders all Jinja2 templates from the bundled domain_repo
    scaffold and writes the resulting files into a new directory named
    `data-meshy-{name}` under the specified output directory.

    It does NOT run terraform or emit events — it only creates files.

    Example:

    \b
      datameshy domain init \\
        --name sales \\
        --account-id 123456789012 \\
        --owner sales-team@company.com
    """
    # Validate inputs
    _validate_domain_name(name)
    if not re.match(r"^\d{12}$", account_id):
        raise typer.BadParameter(f"account-id must be a 12-digit AWS account ID (got: {account_id}).")
    if "@" not in owner:
        raise typer.BadParameter(f"owner must be a valid email address (got: {owner}).")
    if not re.match(r"^\d+\.\d+\.\d+$", platform_version):
        raise typer.BadParameter(f"platform-version must be semver X.Y.Z (got: {platform_version}).")

    dest_root = (output_dir or Path.cwd()) / f"data-meshy-{name}"

    template_vars = {
        "domain": name,
        "account_id": account_id,
        "owner": owner,
        "platform_version": platform_version,
    }

    # Load and render all templates from the bundled domain_repo directory
    templates_pkg = importlib.resources.files("datameshy").joinpath("templates/domain_repo")
    created_files: list[str] = []
    jinja_env = Environment(loader=BaseLoader(), keep_trailing_newline=True)

    def _render_dir(pkg_dir, dest_dir: Path) -> None:
        """Recursively render a package resource directory into dest_dir."""
        for entry in pkg_dir.iterdir():
            entry_name = entry.name
            if entry.is_dir():
                _render_dir(entry, dest_dir / entry_name)
            else:
                dest_name = entry_name[:-3] if entry_name.endswith(".j2") else entry_name
                dest_file = dest_dir / dest_name
                dest_file.parent.mkdir(parents=True, exist_ok=True)

                raw = entry.read_text(encoding="utf-8")
                if entry_name.endswith(".j2"):
                    content = jinja_env.from_string(raw).render(**template_vars)
                else:
                    content = raw
                dest_file.write_text(content, encoding="utf-8")
                created_files.append(str(dest_file.relative_to(dest_root.parent)))

    _render_dir(templates_pkg, dest_root)

    # Print summary
    console.print(f"\n[bold green]Domain repo scaffolded:[/bold green] {dest_root}")
    console.print(f"\n[bold]Files created ({len(created_files)}):[/bold]")
    for f in sorted(created_files):
        console.print(f"  [dim]{f}[/dim]")

    console.print(
        f"\n[bold]Next steps:[/bold]\n"
        f"  1. [cyan]cd {dest_root}[/cyan]\n"
        f"  2. Create a GitHub repo named [cyan]data-meshy-{name}[/cyan] and push\n"
        f"  3. Configure OIDC in the platform: ask your platform team\n"
        f"  4. Bootstrap infra: [cyan]cd infra && terraform init && terraform apply[/cyan]\n"
        f"  5. Add your first data product under [cyan]products/[/cyan]\n"
        f"\nPinned platform version: [yellow]{platform_version}[/yellow]"
    )


@app.command("upgrade")
def domain_upgrade(
    to: Annotated[str, typer.Option("--to", help="Target platform version (e.g. 1.1.0).")],
    dir: Annotated[Optional[Path], typer.Option("--dir", help="Path to existing domain repo root.")] = None,
) -> None:
    """Upgrade an existing domain repo to a new platform version.

    Reads `.datameshy.toml`, updates the pinned `[platform] version`,
    and replaces version references in `infra/main.tf` and all
    `.github/workflows/*.yml` files.

    Safe to run multiple times — the operation is idempotent.

    Example:

    \b
      datameshy domain upgrade --to 1.1.0 --dir ./data-meshy-sales
    """
    import tomllib

    if not re.match(r"^\d+\.\d+\.\d+$", to):
        raise typer.BadParameter(f"--to must be semver X.Y.Z (got: {to}).")

    repo_root = (dir or Path.cwd()).resolve()
    toml_path = repo_root / ".datameshy.toml"

    if not toml_path.is_file():
        console.print("[red]Not a datameshy domain repo:[/red] .datameshy.toml not found.")
        raise typer.Exit(code=1)

    toml_text = toml_path.read_text(encoding="utf-8")

    try:
        config = tomllib.loads(toml_text)
    except Exception as exc:
        console.print(f"[red]Failed to parse .datameshy.toml:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    old_version: str = config.get("platform", {}).get("version", "")
    if not old_version:
        console.print("[red].datameshy.toml is missing [platform] version field.[/red]")
        raise typer.Exit(code=1)

    if old_version == to:
        console.print(f"[yellow]Already at version {to} — nothing to do.[/yellow]")
        return

    changed_lines: list[str] = []

    # 1. Update .datameshy.toml
    new_toml_text = toml_text.replace(
        f'version = "{old_version}"',
        f'version = "{to}"',
        1,  # replace only the first occurrence (platform version)
    )
    if new_toml_text != toml_text:
        toml_path.write_text(new_toml_text, encoding="utf-8")
        changed_lines.append(f"  .datameshy.toml  : version {old_version!r} -> {to!r}")

    # 2. Update infra/main.tf
    main_tf = repo_root / "infra" / "main.tf"
    if main_tf.is_file():
        tf_text = main_tf.read_text(encoding="utf-8")
        new_tf_text = re.sub(
            rf"\?ref=v{re.escape(old_version)}",
            f"?ref=v{to}",
            tf_text,
        )
        if new_tf_text != tf_text:
            main_tf.write_text(new_tf_text, encoding="utf-8")
            changed_lines.append(f"  infra/main.tf    : ?ref=v{old_version} -> ?ref=v{to}")

    # 3. Update .github/workflows/*.yml
    workflows_dir = repo_root / ".github" / "workflows"
    if workflows_dir.is_dir():
        for yml_file in sorted(workflows_dir.glob("*.yml")):
            wf_text = yml_file.read_text(encoding="utf-8")
            new_wf_text = re.sub(
                rf"@v{re.escape(old_version)}",
                f"@v{to}",
                wf_text,
            )
            if new_wf_text != wf_text:
                yml_file.write_text(new_wf_text, encoding="utf-8")
                rel = yml_file.relative_to(repo_root)
                changed_lines.append(f"  {rel}  : @v{old_version} -> @v{to}")

    if changed_lines:
        console.print(f"\n[bold green]Upgraded[/bold green] {old_version} -> {to}:")
        for line in changed_lines:
            console.print(line)
    else:
        console.print(f"[yellow]No version strings found to update for {old_version} -> {to}.[/yellow]")


@app.command("list")
def domain_list(
    ctx: typer.Context,
) -> None:
    """List all onboarded domains in the mesh.

    Queries the mesh-domains DynamoDB table and renders a Rich table.

    Example:

    \b
      datameshy domain list
    """
    try:
        session = _get_session_from_ctx(ctx)
        dynamodb = session.resource("dynamodb")
        table = dynamodb.Table(_DOMAINS_TABLE)
        response = table.scan()
        items = response.get("Items", [])

        if not items:
            console.print("[yellow]No domains found. Run 'datameshy domain onboard' to add one.[/yellow]")
            return

        tbl = Table(title=f"Mesh Domains ({len(items)} total)", show_header=True, header_style="bold cyan")
        tbl.add_column("Domain", style="green")
        tbl.add_column("Account ID")
        tbl.add_column("Owner")
        tbl.add_column("Status")
        tbl.add_column("Onboarded At")

        for item in sorted(items, key=lambda x: x.get("domain", "")):
            tbl.add_row(
                item.get("domain", "-"),
                item.get("account_id", "-"),
                item.get("owner", "-"),
                item.get("status", "-"),
                item.get("onboarded_at", "-"),
            )

        console.print(tbl)

    except Exception as exc:
        console.print(f"[red]Error listing domains:[/red] {exc}")
        raise typer.Exit(code=1) from exc


@app.command("status")
def domain_status(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", help="Domain name to inspect.")],
) -> None:
    """Show details and product count for a domain.

    Example:

    \b
      datameshy domain status --name sales
    """
    _validate_domain_name(name)

    try:
        session = _get_session_from_ctx(ctx)
        dynamodb = session.resource("dynamodb")

        # Fetch domain record
        domains_table = dynamodb.Table(_DOMAINS_TABLE)
        response = domains_table.get_item(Key={"domain": name})
        item = response.get("Item")

        if not item:
            console.print(f"[red]Domain '{name}' not found in mesh-domains.[/red]")
            raise typer.Exit(code=1)

        # Count products for this domain
        products_table = dynamodb.Table(_PRODUCTS_TABLE)
        product_response = products_table.query(
            IndexName="domain-index",
            KeyConditionExpression="domain = :d",
            ExpressionAttributeValues={":d": name},
        )
        product_count = product_response.get("Count", 0)

        tbl = Table(title=f"Domain: {name}", show_header=False, box=None)
        tbl.add_column("Key", style="bold cyan")
        tbl.add_column("Value")

        tbl.add_row("Domain", item.get("domain", "-"))
        tbl.add_row("Account ID", item.get("account_id", "-"))
        tbl.add_row("Owner", item.get("owner", "-"))
        tbl.add_row("Status", item.get("status", "-"))
        tbl.add_row("Onboarded At", item.get("onboarded_at", "-"))
        tbl.add_row("Active Products", str(product_count))

        console.print(tbl)

    except typer.Exit:
        raise
    except Exception as exc:
        console.print(f"[red]Error fetching domain status:[/red] {exc}")
        raise typer.Exit(code=1) from exc
