"""CLI commands for domain management.

Commands:
  datameshy domain onboard  — provision a new domain into the mesh (platform-team command)
  datameshy domain init     — scaffold a new isolated domain repo (domain-team command)
  datameshy domain upgrade  — upgrade an existing domain repo to a new platform version
  datameshy domain list     — list all onboarded domains
  datameshy domain status   — show domain details and product count
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Annotated, Optional

import typer
from rich.console import Console
from rich.table import Table

app = typer.Typer(help="Manage mesh domains (onboard, init, upgrade, list, status).")
console = Console()

_DOMAIN_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9\-]{0,30}[a-zA-Z0-9]$|^[a-zA-Z0-9]$")
_DOMAINS_TABLE = "mesh-domains"
_PRODUCTS_TABLE = "mesh-products"


def _validate_domain_name(name: str) -> str:
    """Validate domain name: alphanumeric + hyphens, max 32 chars."""
    if len(name) > 32:
        raise typer.BadParameter(f"Domain name must be ≤ 32 characters (got {len(name)}).")
    if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]$|^[a-zA-Z0-9]$", name):
        raise typer.BadParameter(
            "Domain name must contain only alphanumeric characters and hyphens, "
            "and must start/end with an alphanumeric character."
        )
    return name


def _get_session_from_ctx(ctx: typer.Context):
    """Retrieve or create a boto3 session from the Typer context."""
    from datameshy.lib.aws_client import get_session

    obj = ctx.ensure_object(dict)
    profile = obj.get("profile")
    region = obj.get("region", "us-east-1")
    return get_session(profile=profile, region=region)


@app.command("onboard")
def domain_onboard(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", help="Domain name (alphanumeric + hyphens, max 32 chars).")],
    account_id: Annotated[str, typer.Option("--account-id", help="AWS account ID for the domain.")],
    owner: Annotated[str, typer.Option("--owner", help="Domain owner email address.")],
    event_bus_arn: Annotated[
        Optional[str],
        typer.Option("--event-bus-arn", help="Central EventBridge event bus ARN.", envvar="MESH_EVENT_BUS_ARN"),
    ] = None,
    dry_run: Annotated[bool, typer.Option("--dry-run", help="Run plan only; do not apply.")] = False,
) -> None:
    """Register a new domain with the central mesh governance (platform-team command).

    This command will:

    \b
    1. Validate domain name and inputs
    2. Scaffold a Terraform environment directory in the platform repo
    3. Run terraform plan and show a summary
    4. Prompt for confirmation before applying
    5. Emit a DomainOnboarded event to the central event bus

    Domain teams should use `datameshy domain init` to scaffold their own
    isolated domain repo after the platform team has run this command.

    Example:

    \b
      datameshy domain onboard \\
        --name sales \\
        --account-id 123456789012 \\
        --owner sales-team@company.com
    """
    # 1. Validate inputs
    _validate_domain_name(name)
    if not re.match(r"^\d{12}$", account_id):
        raise typer.BadParameter(f"account-id must be a 12-digit AWS account ID (got: {account_id}).")
    if "@" not in owner:
        raise typer.BadParameter(f"owner must be a valid email address (got: {owner}).")

    console.print(f"[bold]Onboarding domain:[/bold] [cyan]{name}[/cyan]")
    console.print(f"  Account ID : {account_id}")
    console.print(f"  Owner      : {owner}")

    # 2. Scaffold Terraform environment directory
    env_dir = Path.cwd() / "infra" / "environments" / f"domain-{name}"
    env_dir.mkdir(parents=True, exist_ok=True)

    # Populate terraform.tfvars
    tfvars_content = (
        f'domain      = "{name}"\n'
        f'account_id  = "{account_id}"\n'
        f'owner       = "{owner}"\n'
    )
    tfvars_path = env_dir / "terraform.tfvars"
    tfvars_path.write_text(tfvars_content, encoding="utf-8")

    # Create a minimal main.tf if it doesn't exist
    main_tf = env_dir / "main.tf"
    if not main_tf.exists():
        main_tf.write_text(
            '# Auto-generated by datameshy domain onboard\n'
            '# Customize this file with your domain-specific Terraform configuration.\n\n'
            'module "domain" {\n'
            '  source     = "../../modules/domain-account"\n'
            f'  domain     = "{name}"\n'
            f'  account_id = "{account_id}"\n'
            f'  owner      = "{owner}"\n'
            '}\n',
            encoding="utf-8",
        )

    console.print(f"\n[dim]Terraform environment scaffolded at:[/dim] {env_dir}")

    if dry_run:
        console.print("\n[yellow]--dry-run mode: skipping terraform plan/apply and event emission.[/yellow]")
        console.print(f"\n[green]Domain '{name}' scaffolded.[/green] Review {env_dir} before applying.")
        return

    # 3. Run terraform plan
    from datameshy.lib.terraform_runner import TerraformError, plan

    try:
        console.print("\n[bold]Running terraform plan...[/bold]")
        plan_output = plan(str(env_dir), var_overrides={"domain": name, "account_id": account_id, "owner": owner})
        console.print("[dim]Plan output (credential lines redacted):[/dim]")
        # Show first 40 lines of plan output
        lines = plan_output.splitlines()
        for line in lines[:40]:
            console.print(f"  {line}")
        if len(lines) > 40:
            console.print(f"  [dim]... ({len(lines) - 40} more lines)[/dim]")
    except FileNotFoundError:
        console.print(
            f"[yellow]terraform not found or env directory missing — skipping plan.[/yellow]\n"
            f"[dim]Run `terraform plan` manually in {env_dir}[/dim]"
        )
        plan_output = ""
    except TerraformError as exc:
        console.print(f"[red]terraform plan failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    # 4. Confirm before apply
    if plan_output:
        confirmed = typer.confirm(
            "\nReview the plan above. Apply now?",
            default=False,
        )
        if not confirmed:
            console.print("[yellow]Apply cancelled. Terraform environment is scaffolded and ready.[/yellow]")
            console.print(f"Run manually: cd {env_dir} && terraform apply")
            return

        from datameshy.lib.terraform_runner import apply

        try:
            console.print("\n[bold]Applying...[/bold]")
            apply(str(env_dir), var_overrides={"domain": name, "account_id": account_id, "owner": owner}, auto_approve=True)
            console.print("[green]terraform apply succeeded.[/green]")
        except TerraformError as exc:
            console.print(f"[red]terraform apply failed:[/red] {exc}")
            raise typer.Exit(code=1) from exc

    # 5. Emit DomainOnboarded event
    if event_bus_arn:
        try:
            session = _get_session_from_ctx(ctx)
            from datameshy.lib.aws_client import put_mesh_event

            event_id = put_mesh_event(
                session=session,
                event_bus_arn=event_bus_arn,
                event_type="DomainOnboarded",
                payload={"domain": name, "account_id": account_id, "owner": owner},
            )
            console.print(f"[green]DomainOnboarded event emitted.[/green] event_id={event_id}")
        except Exception as exc:
            console.print(f"[yellow]Warning: could not emit DomainOnboarded event:[/yellow] {exc}")

    # 6. Success summary
    console.print(
        f"\n[bold green]Domain '{name}' onboarded successfully.[/bold green]\n"
        "\nNext steps:\n"
        f"  1. Customize pipeline logic in [cyan]{env_dir}[/cyan]\n"
        "  2. Create your first data product: [cyan]datameshy product create --spec product.yaml[/cyan]\n"
        "  3. List all domains: [cyan]datameshy domain list[/cyan]"
    )


@app.command("list")
def domain_list(
    ctx: typer.Context,
) -> None:
    """List all onboarded domains in the mesh.

    Queries the mesh-domains DynamoDB table and renders a Rich table.

    Example:

    \b
      datameshy domain list
    """
    try:
        session = _get_session_from_ctx(ctx)
        dynamodb = session.resource("dynamodb")
        table = dynamodb.Table(_DOMAINS_TABLE)
        response = table.scan()
        items = response.get("Items", [])

        if not items:
            console.print("[yellow]No domains found. Run 'datameshy domain onboard' to add one.[/yellow]")
            return

        tbl = Table(title=f"Mesh Domains ({len(items)} total)", show_header=True, header_style="bold cyan")
        tbl.add_column("Domain", style="green")
        tbl.add_column("Account ID")
        tbl.add_column("Owner")
        tbl.add_column("Status")
        tbl.add_column("Onboarded At")

        for item in sorted(items, key=lambda x: x.get("domain", "")):
            tbl.add_row(
                item.get("domain", "-"),
                item.get("account_id", "-"),
                item.get("owner", "-"),
                item.get("status", "-"),
                item.get("onboarded_at", "-"),
            )

        console.print(tbl)

    except Exception as exc:
        console.print(f"[red]Error listing domains:[/red] {exc}")
        raise typer.Exit(code=1) from exc


@app.command("status")
def domain_status(
    ctx: typer.Context,
    name: Annotated[str, typer.Option("--name", help="Domain name to inspect.")],
) -> None:
    """Show details and product count for a domain.

    Example:

    \b
      datameshy domain status --name sales
    """
    _validate_domain_name(name)

    try:
        session = _get_session_from_ctx(ctx)
        dynamodb = session.resource("dynamodb")

        # Fetch domain record
        domains_table = dynamodb.Table(_DOMAINS_TABLE)
        response = domains_table.get_item(Key={"domain": name})
        item = response.get("Item")

        if not item:
            console.print(f"[red]Domain '{name}' not found in mesh-domains.[/red]")
            raise typer.Exit(code=1)

        # Count products for this domain
        products_table = dynamodb.Table(_PRODUCTS_TABLE)
        product_response = products_table.query(
            IndexName="domain-index",
            KeyConditionExpression="domain = :d",
            ExpressionAttributeValues={":d": name},
        )
        product_count = product_response.get("Count", 0)

        tbl = Table(title=f"Domain: {name}", show_header=False, box=None)
        tbl.add_column("Key", style="bold cyan")
        tbl.add_column("Value")

        tbl.add_row("Domain", item.get("domain", "-"))
        tbl.add_row("Account ID", item.get("account_id", "-"))
        tbl.add_row("Owner", item.get("owner", "-"))
        tbl.add_row("Status", item.get("status", "-"))
        tbl.add_row("Onboarded At", item.get("onboarded_at", "-"))
        tbl.add_row("Active Products", str(product_count))

        console.print(tbl)

    except typer.Exit:
        raise
    except Exception as exc:
        console.print(f"[red]Error fetching domain status:[/red] {exc}")
        raise typer.Exit(code=1) from exc
