name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/infra-plan.yml"
      - ".github/workflows/infra-apply.yml"
      - ".github/workflows/reusable-infra-plan.yml"

jobs:
  plan-central:
    name: Plan — central
    uses: ./.github/workflows/reusable-infra-plan.yml
    with:
      aws_region: "us-east-1"
      tf_dir: "infra/environments/central"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
